services:
  backend:
    build: ./backend
    container_name: crud-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=flask_crud
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: crud-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15
    container_name: crud-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_crud
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
