version: "3.9"

services:
  db:
    image: postgres:15
    container_name: crud-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_crud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: crud-backend
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/flask_crud
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: crud-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./frontend:/app

volumes:
  postgres_data: